[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
rustflags = [
    "-C",
    "link-arg=--ldproxy-linker=xtensa-esp32s3-elf-gcc",
    # Disable unwinding to prevent _Unwind_Backtrace errors
    "-C",
    "panic=abort",
]

[unstable]
build-std = ["std", "panic_abort"]
build-std-features = ["panic_immediate_abort"]

[env]
ESP_IDF_TOOLS_INSTALL_DIR = "global"
# Don't set IDF_PATH - let esp-idf-sys handle it automatically
