[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
runner = "espflash flash --monitor"

[env]
# Minimal ESP-IDF configuration
ESP_IDF_VERSION = "5.1.2"

[unstable]
build-std = ["std", "panic_abort"]
