[build]
target = "xtensa-esp32s3-espidf"

[target.xtensa-esp32s3-espidf]
linker = "ldproxy"
rustflags = ["-C", "link-arg=--ldproxy-linker=xtensa-esp32s3-elf-gcc"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
# ESP_IDF_VERSION = "5.1.2"
ESP_IDF_TOOLS_INSTALL_DIR = "global"
# Remove or comment out IDF_PATH - let esp-idf-sys handle it
# IDF_PATH = "$HOME/esp/esp-idf"
